Repository Emurgo/cardano-serialization-lib, pull requests merged in 2022-06, with the labels that each got.

#447 Release / 10.2.0
  package-lock.json
  package.json
  rust/Cargo.lock
  rust/Cargo.toml
Labels: release

#449 [babbage] Collateral return and total collateral added to TransactionBody
  rust/src/fakes.rs
  rust/src/lib.rs
  rust/src/serialization.rs
  rust/src/tx_builder.rs
  rust/src/utils.rs
Labels: babbage

#454 [babbage] Collateral return in tx builder
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/tx_builder.rs
  rust/src/tx_builder/tx_inputs_builder.rs
  rust/src/utils.rs
Labels: babbage

#456 [babbage] BlockHeader VRF certs update
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/chain_crypto/algorithms/ed25519.rs
  rust/src/chain_crypto/sign.rs
  rust/src/crypto.rs
  rust/src/fakes.rs
  rust/src/lib.rs
  rust/src/serialization.rs
Labels: babbage

#450 [babbage] Script ref, inlined datum for TransactionOutput, new min ada
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/fakes.rs
  rust/src/lib.rs
  rust/src/output_builder.rs
  rust/src/plutus.rs
  rust/src/serialization.rs
  rust/src/serialization_macros.rs
  rust/src/tx_builder.rs
  rust/src/utils.rs
Labels: babbage

#461 [babbage] Reference inputs
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/lib.rs
  rust/src/serialization.rs
  rust/src/tx_builder.rs
Labels: babbage

#460 [babbage] Protocol params
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/lib.rs
  rust/src/serialization.rs
Labels: babbage

#463 Release / Babbage 11.0.0-beta.1
  package-lock.json
  package.json
  rust/Cargo.lock
  rust/Cargo.toml
  rust/pkg/cardano_serialization_lib.js.flow
Labels: release, babbage

#466 [babbage] Collateral return should not or can not be created in the builder
  rust/src/tx_builder.rs
  rust/src/utils.rs
Labels: babbage
