Repository Emurgo/cardano-serialization-lib, pull requests merged in 2022-02, with the labels that each got.

#314 Bump wasm-bindgen
  rust/Cargo.lock
  rust/Cargo.toml
Labels: bug

#304 Simplify txbuilder output addition
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/fees.rs
  rust/src/lib.rs
  rust/src/output_builder.rs
  rust/src/serialization.rs
  rust/src/tx_builder.rs
  rust/src/utils.rs
Labels: bug

#358 Release / 10.0.0
  package-lock.json
  package.json
  rust/Cargo.lock
  rust/Cargo.toml
  rust/pkg/cardano_serialization_lib.js.flow
  rust/src/output_builder.rs
  rust/src/tx_builder.rs
Labels: release

#361 Release / 10.0.1
  package-lock.json
  package.json
  rust/Cargo.lock
  rust/Cargo.toml
  rust/pkg/cardano_serialization_lib.js.flow
Labels: release

#373 Fixing hash_script_data
  package-lock.json
  package.json
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/plutus.rs
  rust/src/serialization.rs
Labels: in-testing

#376 Release / 10.0.4
  package-lock.json
  package.json
  rust/Cargo.lock
  rust/Cargo.toml
Labels: release
